// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKCxxRAY0USKghGjd1uFmrqz3-cVu4fLw',
    appId: '1:280192320540:web:40bca325cb2cfcce008bd9',
    messagingSenderId: '280192320540',
    projectId: 'shoppingmate-652c6',
    authDomain: 'shoppingmate-652c6.firebaseapp.com',
    storageBucket: 'shoppingmate-652c6.appspot.com',
    measurementId: 'G-9DBW3CNLQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfcIHfsXiJOIInJ-E5gZiNEfaWgNfbYP8',
    appId: '1:280192320540:android:fed76221f74ccbe3008bd9',
    messagingSenderId: '280192320540',
    projectId: 'shoppingmate-652c6',
    storageBucket: 'shoppingmate-652c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqaHTLQF3Tym2brGI19w8HOkna7cB6PZM',
    appId: '1:280192320540:ios:2e3e5ba60aeaa66d008bd9',
    messagingSenderId: '280192320540',
    projectId: 'shoppingmate-652c6',
    storageBucket: 'shoppingmate-652c6.appspot.com',
    androidClientId: '280192320540-vvkn9ahvu97viglkrpv9kr04jok59djs.apps.googleusercontent.com',
    iosClientId: '280192320540-u36q80fa5pu29rn4sreh6dqs93bj6c0m.apps.googleusercontent.com',
    iosBundleId: 'com.hj.smate',
  );
}
